export const authCopy = {
  register: {
    title: "Create an account",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    email: "Email Address",
    emailPlaceholder: "Enter your email address",
    password: "Create Password",
    passwordPlaceholder: "Create a password",
    submit: "Sign up",
    haveAccount: "Already have an account?",
    loginLink: "Login",
    imageAlt:
      "A miniature Japanese noodle stall at night, lit by lanterns — a welcome into the learning space",
  },
  login: {
    title: "Welcome back",
    email: "Email Address",
    emailPlaceholder: "Enter your email address",
    password: "Password",
    passwordPlaceholder: "Enter password",
    submit: "Log in",
    forgot: "Forgot password?",
    noAccount: "Don’t have an account?",
    registerLink: "Sign up",
    imageAlt:
      "A miniature Japanese noodle stall at night, lit by lanterns — a welcome back into the learning space",
  },
  reset: {
    title: "Reset your password",
    hint: "Enter the email on your account. We will send a reset link if it is registered.",
    email: "Email Address",
    emailPlaceholder: "Enter your email address",
    submit: "Send reset link",
    sent: "If that email is registered, we sent a reset link. Check your inbox.",
    updateTitle: "Choose a new password",
    newPassword: "New password",
    newPasswordPlaceholder: "Enter a new password",
    updateSubmit: "Save new password",
    backToLogin: "Back to log in",
    imageAlt:
      "A miniature Japanese noodle stall at night, lit by lanterns — a pause before you return to learning",
  },
  stallImage: "/landing/about-stall.webp",
} as const;
